/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.Lagrange;
import metodos.Newton;
import metodos.Polynomial;
import metodos.Trazadores;
import metodos.hermite;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author robal
 */
public class Home extends javax.swing.JFrame {

    Lagrange lg = new Lagrange();
    Newton nw = new Newton();
    hermite hm = new hermite();
    Cubicos tc = new Cubicos();
    Polynomial p = new Polynomial();
    int i = 0;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Secante
     */
    public Home() {
        initComponents();
        jPanelMuestraGrafica.setVisible(false);
        this.setLocationRelativeTo(null);
        cmbAnio.setVisible(false);
        btnGrafica.setVisible(false);
        ver(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLagrange = new javax.swing.JButton();
        btnDif = new javax.swing.JButton();
        btnNewton = new javax.swing.JButton();
        lblPol = new javax.swing.JLabel();
        cmbFunciones = new javax.swing.JComboBox();
        btnHermite = new javax.swing.JButton();
        btnTrazadores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaResp = new javax.swing.JTextArea();
        cmbAnio = new javax.swing.JComboBox<>();
        btnGrafica = new javax.swing.JButton();
        jPanelMuestraGrafica = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_disabled__undo.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 40, 30));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_active__no.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 30));

        btnLagrange.setText("Metodo Lagrange");
        btnLagrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLagrangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnLagrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 30));

        btnDif.setText("Metodo Diferencias");
        btnDif.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnDifItemStateChanged(evt);
            }
        });
        btnDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDifActionPerformed(evt);
            }
        });
        getContentPane().add(btnDif, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 140, 30));

        btnNewton.setText("Metodo Newton");
        btnNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 30));

        lblPol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPol.setForeground(new java.awt.Color(255, 255, 255));
        lblPol.setText("Respuesta:");
        getContentPane().add(lblPol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, 20));

        cmbFunciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFuncionesItemStateChanged(evt);
            }
        });
        cmbFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFuncionesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, -1));

        btnHermite.setText("Metodo Hermite");
        btnHermite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHermiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnHermite, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, 30));

        btnTrazadores.setText("Metodo Trazadores");
        btnTrazadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrazadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrazadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 140, 30));

        txtaResp.setColumns(20);
        txtaResp.setRows(5);
        jScrollPane1.setViewportView(txtaResp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 420, -1));

        cmbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "años", "1964", "2000", "2010", "2018" }));
        cmbAnio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAnioItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 80, -1));

        btnGrafica.setText("Gráfica");
        btnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));
        getContentPane().add(jPanelMuestraGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 670, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-negro.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Home gn = new Home();
        gn.show();
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLagrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagrangeActionPerformed
        Oculta();
        ver(true);
        i = 1;

        cmbFunciones.removeAllItems();
        cmbFunciones.addItem("SELECCIONE");
        cmbFunciones.addItem("Ejercicio 1");
        cmbFunciones.addItem("Ejercicio 3");
        cmbFunciones.addItem("Ejercicio 4");

    }//GEN-LAST:event_btnLagrangeActionPerformed

    private void btnNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewtonActionPerformed
        Oculta();
        ver(true);
        i = 2;
        cmbFunciones.removeAllItems();
        cmbFunciones.addItem("SELECCIONE");
        cmbFunciones.addItem("Ejercicio 1");
        cmbFunciones.addItem("Ejercicio 3");

    }//GEN-LAST:event_btnNewtonActionPerformed

    private void cmbFuncionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFuncionesItemStateChanged
        double n = 0;

        limpiar();
        switch (i) {
            //ver que boton elegio
            case 1:
                //elegir ejercicio
                switch (cmbFunciones.getSelectedIndex()) {
                    case 1:
                        cmbAnio.setVisible(true);
                        btnGrafica.setVisible(false);
                        break;
                    case 2:
                        double x[] = {0, Math.PI / 3, Math.PI / 2};
                        double y[] = {0, 0.6353845729, -2.243601471};
                        cmbAnio.setVisible(false);
                        String cadena[] = lg.Lagrange(x, y, Math.PI / 4);
                        txtaResp.setText(cadena[0]);
                        btnGrafica.setVisible(true);
                        break;
                    case 3:
                        double a[] = {0, Math.PI / 4, Math.PI / 2};
                        double b[] = {0, Math.sqrt(2) / 2, 1};
                        cmbAnio.setVisible(false);
                        String cadena1[] = lg.Lagrange(a, b, Math.PI / 6);
                        txtaResp.setText(cadena1[0] + "\n" + "Evaluado pi/6" + "\n" + cadena1[1] + "\n" + cadena1[2]);
                        btnGrafica.setVisible(true);
                        break;
                    default:
                        break;
                }

                break;
            case 2:
                switch (cmbFunciones.getSelectedIndex()) {
                    case 1:
                        cmbAnio.setVisible(true);
                        btnGrafica.setVisible(false);
                        break;
                    case 2:
                        double x[] = {0, Math.PI / 3, Math.PI / 2};
                        double y[] = {0, 0.6353845729, -2.243601471};
                        cmbAnio.setVisible(false);
                        String cadena[] = nw.Newton(x, y, Math.PI / 4);
                        txtaResp.setText(cadena[0]);
                        btnGrafica.setVisible(true);
                        break;
                    default:
                        break;
                }
                break;
            case 3:
                switch (cmbFunciones.getSelectedIndex()) {
                    case 1:
                        cmbAnio.setVisible(true);
                        btnGrafica.setVisible(false);
                        break;
                    case 2:
                        btnGrafica.setVisible(false);
                        double x[] = {0, 2, 5, 6};
                        double y[] = {3, 6, 10.5, 24};
                        cmbAnio.setVisible(false);
                        String cadena[] = nw.Newton(x, y, 4);
                        txtaResp.setText(cadena[2] + "\n" + cadena[0] + "\n" + "Evaluado 4" + "\n" + cadena[1] + "\n" + cadena[3]);
                        break;
                    case 3:
                        btnGrafica.setVisible(true);
                        double a[] = {0, Math.PI / 4, Math.PI / 2};
                        double b[] = {0, Math.sqrt(2) / 2, 1};
                        cmbAnio.setVisible(false);
                        String cadena1[] = nw.Newton(a, b, Math.PI / 6);
                        txtaResp.setText(cadena1[2] + "\n" + cadena1[0] + "\n" + "Evaluado pi/6" + "\n" + cadena1[1] + "\n" + cadena1[3]);
                        break;
                    default:
                        break;
                }
                break;
            case 4:
                switch (cmbFunciones.getSelectedIndex()) {
                    case 1:
                        cmbAnio.setVisible(true);
                        btnGrafica.setVisible(false);
                        break;
                    case 2:
                        double x[] = {0,0, Math.PI / 3, Math.PI / 3, Math.PI / 2, Math.PI / 2};
                        double x1[]={p.Ecuacion(p.Derivar("x^2cos(5x+2)"), 0),p.Ecuacion(p.Derivar("x^2cos(5x+2)"), Math.PI / 3),p.Ecuacion(p.Derivar("x^2cos(5x+2)"), Math.PI / 2)};
                        double y1[]={0};
                        double y[] = {0, 0.6353845729, -2.243601471};
                        cmbAnio.setVisible(false);
                        String cadena[] = hm.Hermite(x, y, x1,y1, (Math.PI / 4));
                        txtaResp.setText(cadena[0]);
                        btnGrafica.setVisible(true);
                        break;
                    case 3:
                        double a[] = {0, Math.PI / 4, Math.PI / 2};
                        double x2[]={p.Ecuacion(p.Derivar("sen(x)"), 0),p.Ecuacion(p.Derivar("sen(x)"), Math.PI / 4),p.Ecuacion(p.Derivar("x^2cos(5x+2)"), Math.PI / 2)};
                        double y2[]={0};
                        double b[] = {0, Math.sqrt(2) / 2, 1};
                        cmbAnio.setVisible(false);
                        String cadena1[] = hm.Hermite(a, b, x2, y2,Math.PI / 6);
                        txtaResp.setText(cadena1[0] + "\n" + "Evaluado pi/6" + "\n" + cadena1[1] + "\n" + cadena1[2]);
                        btnGrafica.setVisible(true);
                        break;
                    case 4:
                        double c[] = {0,1};
                        double c1[]={-2,0};
                        double d1[]={6,-8};
                        double d[] = {1, 1};
                        cmbAnio.setVisible(false);
                        String cadena2[] = hm.Hermite(c, d, c1, d1, 2);
                        txtaResp.setText(cadena2[0] + "\n" + "Evaluado 2" + "\n" + cadena2[1] + "\n" + cadena2[2]);
                        btnGrafica.setVisible(true);
                        break;
                    default:
                        break;
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbFuncionesItemStateChanged

    private void cmbFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFuncionesActionPerformed

    }//GEN-LAST:event_cmbFuncionesActionPerformed

    private void btnDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDifActionPerformed
        Oculta();
        ver(true);
        i = 3;
        cmbFunciones.removeAllItems();
        cmbFunciones.addItem("SELECCIONE");
        cmbFunciones.addItem("Ejercicio 1");
        cmbFunciones.addItem("Ejercicio 2");
        cmbFunciones.addItem("Ejercicio 4");

    }//GEN-LAST:event_btnDifActionPerformed

    private void btnDifItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnDifItemStateChanged
        Oculta();
        ver(true);
    }//GEN-LAST:event_btnDifItemStateChanged

    private void btnHermiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHermiteActionPerformed
        Oculta();
        ver(true);
        i = 4;
        cmbFunciones.removeAll();
        cmbFunciones.addItem("SELECCIONE");
        cmbFunciones.addItem("Ejercicio 1");
        cmbFunciones.addItem("Ejercicio 3");
        cmbFunciones.addItem("Ejercicio 4");
        cmbFunciones.addItem("Ejercicio 6");

    }//GEN-LAST:event_btnHermiteActionPerformed

    private void btnTrazadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrazadoresActionPerformed
        // TODO add your handling code here:
        Oculta();
        ver(true);
        i = 5;
        tc.show();
        this.setVisible(false);
    }//GEN-LAST:event_btnTrazadoresActionPerformed

    private void cmbAnioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAnioItemStateChanged
        // TODO add your handling code here:
        double x[] = {1910, 1930, 1950, 1960, 1980};
        double x1[] = {1, 2, 3, 4, 5};
        double y1[] = {0};
        double y[] = {125350, 133420, 117183, 120323, 145311};
        if (i == 1) {
            switch (cmbAnio.getSelectedIndex()) {
                case 1: {
                    String cadena[] = lg.Lagrange(x, y, 1964);
                    txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[2]);
                    break;
                }
                case 2: {
                    String cadena[] = lg.Lagrange(x, y, 2000);
                    txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[2]);
                    break;
                }
                case 3: {
                    String cadena[] = lg.Lagrange(x, y, 2010);
                    txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[2]);
                    break;
                }
                case 4: {
                    String cadena[] = lg.Lagrange(x, y, 2018);
                    txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[2]);
                    break;
                }
                default:
                    break;
            }
        } else if (i == 2) {
            switch (cmbAnio.getSelectedIndex()) {
                case 1: {
                    String cadena[] = nw.Newton(x, y, 1964);
                    txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 2: {
                    String cadena[] = nw.Newton(x, y, 2000);
                    txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 3: {
                    String cadena[] = nw.Newton(x, y, 2010);
                    txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 4: {
                    String cadena[] = nw.Newton(x, y, 2018);
                    txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                default:
                    break;
            }
        } else if (i == 3) {
            switch (cmbAnio.getSelectedIndex()) {
                case 1: {
                    String cadena[] = nw.Newton(x, y, 1964);
                    txtaResp.setText(cadena[2] + "\n" + cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 2: {
                    String cadena[] = nw.Newton(x, y, 2000);
                    txtaResp.setText(cadena[2] + "\n" + cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 3: {
                    String cadena[] = nw.Newton(x, y, 2010);
                    txtaResp.setText(cadena[2] + "\n" + cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 4: {
                    String cadena[] = nw.Newton(x, y, 2018);
                    txtaResp.setText(cadena[2] + "\n" + cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                default:
                    break;
            }
        } else if(i==4){
        switch (cmbAnio.getSelectedIndex()) {
                case 1: {
                    // String cadena[] = hm.Hermite(x, y, x1, y1, 1964);
                    //txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 2: {
                    // String cadena[] = hm.Hermite(x, y, x1, y1, 2000);
                    //txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 3: {
                    // String cadena[] = hm.Hermite(x, y, x1, y1, 2010);
                    //txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                case 4: {
                    // String cadena[] = hm.Hermite(x, y, x1, y1, 2018);
                    //txtaResp.setText(cadena[0] + "\n" + cadena[1] + "\n" + cadena[3]);
                    break;
                }
                default:
                    break;
            }
        }

    }//GEN-LAST:event_cmbAnioItemStateChanged

    private void btnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaActionPerformed
        // TODO add your handling code here:
        lblPol.setVisible(false);
        cmbFunciones.setVisible(false);
        txtaResp.setVisible(false);
        btnGrafica.setVisible(false);
        jPanelMuestraGrafica.setVisible(true);
        ChartPanel panel = null;
        JFreeChart chart = null;
        if (i == 1) {
            XYSeries series = new XYSeries("");
            if (cmbFunciones.getSelectedIndex() == 2) {
                double i = 0;
                do {
                    series.add(i, 4.676884835247799 * i - 3.886694785858488 * Math.pow(i, 2));
                    i = i + 0.01;
                } while (i <= Math.PI / 2);
            } else if (cmbFunciones.getSelectedIndex() == 3) {
                double i = 0;
                do {
                    series.add(i, 1.1640128599466308 * i - 0.3357488673628104 * Math.pow(i, 2));
                    i = i + 0.01;
                } while (i <= Math.PI / 2);
            }
            XYSplineRenderer renderer = new XYSplineRenderer();
            XYSeriesCollection dataset = new XYSeriesCollection();
            dataset.addSeries(series);
            ValueAxis x = new NumberAxis();
            ValueAxis y = new NumberAxis();
            XYSeries serie = new XYSeries("datos");
            XYPlot plot;
            jPanelMuestraGrafica.removeAll();
            x.setLabel(" EJE X");
            y.setLabel(" EJE Y");
//
            plot = new XYPlot(dataset, x, y, renderer);
            chart = new JFreeChart(plot);
//
            chart.setTitle("Grafico");
//
            panel = new ChartPanel(chart);
            panel.setBounds(5, 10, 600, 450);
            jPanelMuestraGrafica.add(panel);
            jPanelMuestraGrafica.repaint();

        } else if (i == 2) {
            XYSeries series = new XYSeries("");
            double i = 0;
            do {
                series.add(i, 4.6768848352478 * i - 3.8866947858584884 * Math.pow(i, 2));
                i = i + 0.01;
            } while (i <= Math.PI / 2);
            XYSplineRenderer renderer = new XYSplineRenderer();
            XYSeriesCollection dataset = new XYSeriesCollection();
            dataset.addSeries(series);
            ValueAxis x = new NumberAxis();
            ValueAxis y = new NumberAxis();
            XYSeries serie = new XYSeries("datos");
            XYPlot plot;
            jPanelMuestraGrafica.removeAll();
            x.setLabel(" EJE X");
            y.setLabel(" EJE Y");
//
            plot = new XYPlot(dataset, x, y, renderer);
            chart = new JFreeChart(plot);
//
            chart.setTitle("Grafico");
//
            panel = new ChartPanel(chart);
            panel.setBounds(5, 10, 600, 450);
            jPanelMuestraGrafica.add(panel);
            jPanelMuestraGrafica.repaint();
        } else if (i == 3) {
            XYSeries series = new XYSeries("");
            double i = 0;
            do {
                series.add(i, 1.1640128599466308 * i - 0.33574886736281045 * Math.pow(i, 2));
                i = i + 0.01;
            } while (i <= Math.PI / 2);
            XYSplineRenderer renderer = new XYSplineRenderer();
            XYSeriesCollection dataset = new XYSeriesCollection();
            dataset.addSeries(series);
            ValueAxis x = new NumberAxis();
            ValueAxis y = new NumberAxis();
            XYSeries serie = new XYSeries("datos");
            XYPlot plot;
            jPanelMuestraGrafica.removeAll();
            x.setLabel(" EJE X");
            y.setLabel(" EJE Y");
//
            plot = new XYPlot(dataset, x, y, renderer);
            chart = new JFreeChart(plot);
//
            chart.setTitle("Grafico");
//
            panel = new ChartPanel(chart);
            panel.setBounds(5, 10, 600, 450);
            jPanelMuestraGrafica.add(panel);
            jPanelMuestraGrafica.repaint();
        } else if (i == 4) {
            XYSeries series = new XYSeries(""); 
//
            if (cmbFunciones.getSelectedIndex() == 2) {
                double i = 0;
                do {
                    series.add(i, 4.676884835247799 * i - 3.886694785858488 * Math.pow(i, 2));
                    i = i + 0.01;
                } while (i <= Math.PI / 2);
            } else if (cmbFunciones.getSelectedIndex() == 3) {
                double i = 0;
                do {
                    series.add(i, 1.1640128599466308 * i - 0.3357488673628104 * Math.pow(i, 2));
                    i = i + 0.01;
                } while (i <= Math.PI / 2);
            }
            XYSplineRenderer renderer = new XYSplineRenderer();
            XYSeriesCollection dataset = new XYSeriesCollection();
            dataset.addSeries(series);
            ValueAxis x = new NumberAxis();
            ValueAxis y = new NumberAxis();
            XYSeries serie = new XYSeries("datos");
            XYPlot plot;
            jPanelMuestraGrafica.removeAll();
            x.setLabel(" EJE X");
            y.setLabel(" EJE Y");
//
            plot = new XYPlot(dataset, x, y, renderer);
            chart = new JFreeChart(plot);
//
            chart.setTitle("Grafico");
//
            panel = new ChartPanel(chart);
            panel.setBounds(5, 10, 600, 450);
            jPanelMuestraGrafica.add(panel);
            jPanelMuestraGrafica.repaint();
        }

    }//GEN-LAST:event_btnGraficaActionPerformed
    public void ver(boolean i) {
        cmbFunciones.setVisible(i);
        jScrollPane1.setVisible(i);
        txtaResp.setVisible(i);
        lblPol.setVisible(i);

    }

    public void Oculta() {
        btnDif.setVisible(false);
        btnHermite.setVisible(false);
        btnTrazadores.setVisible(false);
        btnLagrange.setVisible(false);
        btnNewton.setVisible(false);

    }

    public void limpiar() {
        int row = model.getRowCount();
        for (int k = 0; k < row; k++) {
            model.removeRow(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDif;
    private javax.swing.JButton btnGrafica;
    private javax.swing.JButton btnHermite;
    private javax.swing.JButton btnLagrange;
    private javax.swing.JButton btnNewton;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTrazadores;
    private javax.swing.JComboBox<String> cmbAnio;
    private javax.swing.JComboBox cmbFunciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelMuestraGrafica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPol;
    private javax.swing.JTextArea txtaResp;
    // End of variables declaration//GEN-END:variables
}
