/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;


import javax.swing.table.DefaultTableModel;
import metodos.Lagrange;
import metodos.Newton;
import metodos.Trazadores;
import metodos.hermite;

/**
 *
 * @author robal
 */
public class Home extends javax.swing.JFrame {

   Lagrange lg = new Lagrange();
    Newton nw = new Newton();
    Trazadores tc = new Trazadores();
    hermite hm = new hermite();

    int i = 0;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Secante
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        ver(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLagrange = new javax.swing.JButton();
        btnDif = new javax.swing.JButton();
        btnTart = new javax.swing.JButton();
        lblPol = new javax.swing.JLabel();
        cmbFunciones = new javax.swing.JComboBox();
        txtPolinomio = new javax.swing.JTextField();
        btnHermite = new javax.swing.JButton();
        btnTrazadores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_disabled__undo.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 40, 30));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_active__no.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 40, 30));

        btnLagrange.setText("Metodo Lagrange");
        btnLagrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLagrangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnLagrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 30));

        btnDif.setText("Metodo Diferencias");
        btnDif.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnDifItemStateChanged(evt);
            }
        });
        btnDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDifActionPerformed(evt);
            }
        });
        getContentPane().add(btnDif, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 140, 30));

        btnTart.setText("Metodo Newton");
        btnTart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTartActionPerformed(evt);
            }
        });
        getContentPane().add(btnTart, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, 30));

        lblPol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPol.setForeground(new java.awt.Color(255, 255, 255));
        lblPol.setText("Polinomio");
        getContentPane().add(lblPol, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, 20));

        cmbFunciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFuncionesItemStateChanged(evt);
            }
        });
        cmbFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFuncionesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 250, -1));
        getContentPane().add(txtPolinomio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 250, 40));

        btnHermite.setText("Metodo Hermite");
        btnHermite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHermiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnHermite, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 30));

        btnTrazadores.setText("Metodo Trazadores");
        btnTrazadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrazadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrazadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-negro.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Home gn = new Home();
        gn.show();
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLagrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagrangeActionPerformed
        Oculta();
        ver(true);
        i = 1;

        cmbFunciones.removeAllItems();
        cmbFunciones.addItem("Ejercicio 1a");
        cmbFunciones.addItem("Ejercicio 1b");
        cmbFunciones.addItem("Ejercicio 3a");
        cmbFunciones.addItem("Ejercicio 3b");
        cmbFunciones.addItem("e^(3x-3) -ln(x-1)^2+1");
        cmbFunciones.addItem("cos(0.785-x(1+x^2)^1/2)");

    }//GEN-LAST:event_btnLagrangeActionPerformed

    private void btnTartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTartActionPerformed
        Oculta();
        ver(true);
        i = 2;
        cmbFunciones.removeAllItems();
        cmbFunciones.addItem("x^3 +3x -1");
        cmbFunciones.addItem("x^3 -4.65x^2 -49.92x -76.69");
        
        
    }//GEN-LAST:event_btnTartActionPerformed

    private void cmbFuncionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFuncionesItemStateChanged
        
    }//GEN-LAST:event_cmbFuncionesItemStateChanged

    private void cmbFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFuncionesActionPerformed

    }//GEN-LAST:event_cmbFuncionesActionPerformed

    private void btnDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDifActionPerformed
        Oculta();
        ver(true);
        i = 3;
        cmbFunciones.removeAllItems();
        cmbFunciones.addItem("x^4 +x^3 +0.56x^2 -1.44x -2.88");
        cmbFunciones.addItem("x^4 -3x^2 +5x +2");
        
    }//GEN-LAST:event_btnDifActionPerformed

    private void btnDifItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnDifItemStateChanged
        Oculta();
        ver(true);
    }//GEN-LAST:event_btnDifItemStateChanged

    private void btnHermiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHermiteActionPerformed
        Oculta();
        ver(true);
        i = 4;
        cmbFunciones.removeAll();
        cmbFunciones.addItem("x^3 +3x -1");
        cmbFunciones.addItem("x^3 -4.65x^2 -49.92x -76.69");
        cmbFunciones.addItem("x^4 +x^3 +0.56x^2 -1.44x -2.88");
        cmbFunciones.addItem("x^4 -3x^2 +5x +2");
        cmbFunciones.addItem("x^5 -3x^4 -23x^3 +55x^2 +74x -120");
        cmbFunciones.addItem("x^6 -7x^4 +x^3 +3x -1");

    }//GEN-LAST:event_btnHermiteActionPerformed

    private void btnTrazadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrazadoresActionPerformed
        // TODO add your handling code here:
        Oculta();
        ver(true);
        i = 5;
        cmbFunciones.removeAllItems();
        cmbFunciones.addItem("x^3 +3x -1");
        cmbFunciones.addItem("x^3 -4.65x^2 -49.92x -76.69");
        cmbFunciones.addItem("x^4 +x^3 +0.56x^2 -1.44x -2.88");
        cmbFunciones.addItem("x^4 -3x^2 +5x +2");
        cmbFunciones.addItem("x^5 -3x^4 -23x^3 +55x^2 +74x -120");
        cmbFunciones.addItem("x^6 -7x^4 +x^3 +3x -1");
        cmbFunciones.addItem("ln(1+x) -cos(x)");
        cmbFunciones.addItem("10sin(x) +3cos(x)");
        cmbFunciones.addItem("e^(3x-3) -ln(x-1)^2 +1");
    }//GEN-LAST:event_btnTrazadoresActionPerformed
    public void ver(boolean i) {
        cmbFunciones.setVisible(i);
        txtPolinomio.setVisible(i);
        lblPol.setVisible(i);

    }

    public void Oculta() {
        btnDif.setVisible(false);
        btnHermite.setVisible(false);
        btnTrazadores.setVisible(false);
        btnLagrange.setVisible(false);
        btnTart.setVisible(false);

    }

    public void limpiar() {
        int row = model.getRowCount();
        for (int k = 0; k < row; k++) {
            model.removeRow(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDif;
    private javax.swing.JButton btnHermite;
    private javax.swing.JButton btnLagrange;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTart;
    private javax.swing.JButton btnTrazadores;
    private javax.swing.JComboBox cmbFunciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPol;
    private javax.swing.JTextField txtPolinomio;
    // End of variables declaration//GEN-END:variables
}
